# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Gemeinden"
#  pageRef = "gemeinden"
#  weight = 10

[[main]]
  name = "Gemeinde Jena"
  pageRef = "gemeinden/jena"
  #parent = "Gemeinden"
  weight = 10
  
#[[main]]
#  name = "Bad Klosterlausnitz"
#  pageRef = "gemeinden/klosterlausnitz"
#  parent = "Gemeinden"
#  weight = 20
  
#[[main]]
#  name = "Pastoren"
#  pageRef = "gemeinden/pastoren"
#  parent = "Gemeinden"
#  weight = 30

#[[main]]
#  name = "Beiträge"
#  pageRef = "beitraege"
#  weight = 20

[[main]]
  name = "Angedacht"
  pageRef = "beitraege/angedacht"
  #parent = "Beiträge"
  #weight = 10
  weight = 20
  
#[[main]]
#  name = "Aus dem Gemeindeleben"
#  pageRef = "beitraege/gemeindeleben"
#  parent = "Beiträge"
#  weight = 20

[[main]]
  name = "Gemeindebriefe"
  pageRef = "downloads/gemeindebrief"
  weight = 30

#[[main]]
#  name = "Termine"
#  pageRef = "termine"
#  weight = 40
#  [main.params]
#    icon = "calendar-regular"
  
#[[main]]
#  name = "Kalender"
#  pageRef = "termine/kalender"
#  parent = "Termine"
#  weight = 10

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

#[[main]]
#  identifier = "locale"
#  weight = 100
#  [main.params]
#    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Datenschutz"
  pageRef = "datenschutz"
  weight = 10
  
[[footer]]
  name = "Impressum"
  pageRef = "impressum"
  weight = 20
  
